### ISSUE TITLE
setup.py fails on MacOSX

### ISSUE THREAD

**Issue by subatomicglue** [cmcginty/mktoc#7]
So, I cloned the repo, read the README and didn't see any instructions for install, and I didn't see any script I could run like mktoc in the clone....     but I saw setup.py, so I tried to run it, and...  this is what I get:

```
Traceback (most recent call last):
  File "./setup.py", line 17, in <module>
    import mktoc
  File "/Users/kevin/skydrive/Music/iPhone6 Recorder/mktoc/mktoc/__init__.py", line 166, in <module>
    import mktoc.cmdline
  File "/Users/kevin/skydrive/Music/iPhone6 Recorder/mktoc/mktoc/cmdline.py", line 15, in <module>
    import chardet.universaldetector
ImportError: No module named chardet.universaldetector
```

I'm on MacOSX...
```
bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

python --version
Python 2.7.12
```

**Comment by subatomicglue** [comment]
I also noticed this page linked far at the bottom of your GitHub...   I ventured a click...
Looks like a python module, ok, ... I tried it...

```
pip install mktoc --upgrade --user
Collecting mktoc
  Could not find a version that satisfies the requirement mktoc (from versions: )
No matching distribution found for mktoc
```

Ideas?

**Comment by cmcginty** [comment]
Sorry, I've only tested on Ubuntu. I'll see if I can get it working on OSX
